stages:
  - build

build-gitlab:
  stage: build
  image: alpinelinux/docker-compose
  script:
    - >-
      apk add -X https://dl-cdn.alpinelinux.org/alpine/edge/community
      go-task
      curl
    - go-task build-args
    - go-task build
  tags: [ci-docker-image, x86_64]
