version: '3.5'
services:
  gitlab:
    image: supar/gitlab:$GITLAB_VERSION
    build:
      context: .
      args:
        - ALPINE_VERSION
        - RUBY_VERSION
        - GITLAB_VERSION
        - GITLAB_SHELL_VERSION
    hostname: ${GITLAB_HOSTNAME:-gitlab}
    restart: always
    ports:
      - 127.0.0.1:8181:8181
    volumes:
      - ${GITLAB_STORAGE_ROOT:-./storage}/repositories:/home/git/repositories
      - ${GITLAB_CONFIG_ROOT:-./storage}:/etc/gitlab
      - ${GITLAB_LOG_ROOT:-./storage}:/var/log
      - ${GITLAB_STORAGE_ROOT:-./storage}/builds:/home/git/gitlab/builds
      - ${GITLAB_STORAGE_ROOT:-./storage}/shared:/home/git/gitlab/shared
      - ${GITLAB_STORAGE_ROOT:-./storage}/uploads:/home/git/gitlab/public/uploads
      - ${GITLAB_STORAGE_ROOT:-./storage}/plugins:/home/git/gitlab/plugins
      - ssh-authorized-keys:/home/git/.ssh/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
      - sockets:/home/git/run/
    depends_on:
      - redis
      - gitaly
      - gitlab-shell
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - GITLAB_ROOT_PASSWORD
      - GITLAB_BACKUP_SKIP
      - GITLAB_SERVICES
  gitaly:
    image: alpinelinux/gitaly:$GITALY_SERVER_VERSION
    init: true
    restart: always
    build:
      context: ./gitaly
      args:
        - ALPINE_VERSION
        - RUBY_VERSION
        - GITALY_SERVER_VERSION
        - GITLAB_SHELL_VERSION
    depends_on:
      - gitlab-shell # for gitlab-secret
    volumes:
      - ./storage/repositories:/home/git/repositories
      - ./storage/config/gitaly/:/etc/gitlab/gitaly
      - ./storage/config/gitlab-shell:/etc/gitlab/gitlab-shell
      - ./storage/log/gitaly:/var/log/gitaly
      - sockets:/home/git/run/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
  gitlab-shell:
    image: alpinelinux/gitlab-shell:$GITLAB_SHELL_VERSION
    restart: always
    build:
      context: ./gitlab-shell
      args:
        - ALPINE_VERSION
        - GITLAB_SHELL_VERSION
    ports:
      - 2222:22
    volumes:
      - ./storage/config/gitlab-shell:/etc/gitlab/gitlab-shell
      - ./storage/config/ssh:/etc/gitlab/ssh
      - ./storage/log:/var/log
      - ssh-authorized-keys:/home/git/.ssh/
      - sockets:/home/git/run/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./storage/redis:/data
    entrypoint: redis-server --appendonly yes

volumes:
  sockets:
  ssh-authorized-keys:
  gitlab-secret:
