version: '3.5'
services:
  gitlab:
    image: alpinelinux/alpine-docker-gitlab
    build:
      context: .
      args:
        - GITLAB_SHELL_VERSION
    hostname: ${GITLAB_HOSTNAME:-gitlab}
    restart: always
    volumes:
      - /srv/docker/gitlab/repositories:/home/git/repositories
      - /srv/docker/gitlab/config:/etc/gitlab
      - /srv/docker/gitlab/log:/var/log
      - /srv/docker/gitlab/builds:/home/git/gitlab/builds
      - /srv/docker/gitlab/shared:/home/git/gitlab/shared
      - /srv/docker/gitlab/uploads:/home/git/gitlab/public/uploads
      - /srv/docker/gitlab/plugins:/home/git/gitlab/plugins
      - ssh-authorized-keys:/home/git/.ssh/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
      - gitlab-socket:/home/git/gitlab/tmp/sockets/
      - gitaly-socket:/home/git/gitlab/tmp/sockets/private
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - redis
      - gitaly
      - gitlab-shell
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - GITLAB_ROOT_PASSWORD
      - GITLAB_BACKUP_SKIP
      - GITLAB_SERVICES
  gitaly:
    image: alpinelinux/gitaly:$GITALY_SERVER_VERSION
    build:
      context: ./gitaly
      args:
        - GITALY_SERVER_VERSION
        - GITLAB_SHELL_VERSION
    depends_on:
      - gitlab-shell # for gitlab-secret
    volumes:
      - /srv/docker/gitlab/repositories:/home/git/repositories
      - /srv/docker/gitlab/config/gitaly/:/etc/gitlab/gitaly
      - /srv/docker/gitlab/config/gitlab-shell:/etc/gitlab/gitlab-shell
      - gitaly-socket:/home/git/run/gitaly
      - gitlab-socket:/home/git/run/gitlab
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
  gitlab-shell:
    image: alpinelinux/gitlab-shell:$GITLAB_SHELL_VERSION
    build:
      context: ./gitlab-shell
      args:
        - GITLAB_SHELL_VERSION
    volumes:
      - /srv/docker/gitlab/config/gitlab-shell:/etc/gitlab/gitlab-shell
      - /srv/docker/gitlab/config/ssh:/etc/gitlab/ssh
      - /srv/docker/gitlab/log:/var/log
      - ssh-authorized-keys:/home/git/.ssh/
      - gitlab-socket:/home/git/run/gitlab
      - gitaly-socket:/home/git/gitlab/tmp/sockets/private
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - /srv/docker/gitlab/postgres12:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - /srv/docker/gitlab/redis:/data
    entrypoint: redis-server --appendonly yes

volumes:
  gitaly-socket:
  gitlab-socket:
  ssh-authorized-keys:
  gitlab-secret:
