version: '3.5'
services:
  gitlab:
    image: alpinelinux/alpine-docker-gitlab
    build:
      context: .
      args:
        ALPINE_VERSION: 3.13
        RUBY_VERSION: 2.7
    hostname: ${GITLAB_HOSTNAME:-gitlab}
    restart: always
    volumes:
      - /srv/docker/gitlab/repositories:/home/git/repositories
      - /srv/docker/gitlab/config:/etc/gitlab
      - /srv/docker/gitlab/log:/var/log
      - /srv/docker/gitlab/builds:/home/git/gitlab/builds
      - /srv/docker/gitlab/shared:/home/git/gitlab/shared
      - /srv/docker/gitlab/uploads:/home/git/gitlab/public/uploads
      - /srv/docker/gitlab/plugins:/home/git/gitlab/plugins
    ports:
      - "2222:22"
      - "8080:80"
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - GITLAB_ROOT_PASSWORD
      - GITLAB_BACKUP_SKIP
      - GITLAB_USE_PUMA
      - GITLAB_SERVICES
  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - /srv/docker/gitlab/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - /srv/docker/gitlab/redis:/data
    entrypoint: redis-server --appendonly yes

