version: '3.5'
services:
  gitlab:
    image: supar/gitlab:$GITLAB_VERSION
    build:
      context: .
      args:
        - ALPINE_VERSION
        - RUBY_VERSION
        - GITLAB_VERSION
        - GITLAB_SHELL_VERSION
        - GITALY_SERVER_VERSION
    hostname: ${GITLAB_HOSTNAME:-gitlab}
    restart: always
    ports:
      - 127.0.0.1:8181:8181
    volumes:
      - ${GITLAB_STORAGE_ROOT:-./storage}/repositories:/home/git/repositories
      - ${GITLAB_CONFIG_ROOT:-./storage/config}:/etc/gitlab
      - ${GITLAB_LOG_ROOT:-./storage/log}:/var/log
      - ${GITLAB_STORAGE_ROOT:-./storage}/builds:/home/git/gitlab/builds
      - ${GITLAB_STORAGE_ROOT:-./storage}/shared:/home/git/gitlab/shared
      - ${GITLAB_STORAGE_ROOT:-./storage}/uploads:/home/git/gitlab/public/uploads
      - ${GITLAB_STORAGE_ROOT:-./storage}/plugins:/home/git/gitlab/plugins
      - ${GITLAB_STORAGE_ROOT:-./storage}/certs/registry:/home/git/certs/registry
      - ssh-authorized-keys:/home/git/.ssh/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
      - sockets:/home/git/run/
    depends_on:
      - redis
      - gitaly
      - gitlab-shell
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - REGISTRY_S3_ACCESSKEY
      - REGISTRY_S3_SECRET
      - REGISTRY_S3_REGION
      - REGISTRY_S3_ENDPOINT
      - REGISTRY_S3_BUCKET
      - REGISTRY_S3_ROOTDIR
      - REGISTRY_TOKEN_REALM
  gitaly:
    image: alpinelinux/gitaly:$GITALY_SERVER_VERSION
    init: true
    restart: always
    build:
      context: ./gitaly
      args:
        - ALPINE_VERSION
        - RUBY_VERSION
        - GITALY_SERVER_VERSION
        - GITLAB_SHELL_VERSION
    depends_on:
      - gitlab-shell # for gitlab-secret
    volumes:
      - ${GITLAB_STORAGE_ROOT:-./storage}/repositories:/home/git/repositories
      - ${GITLAB_CONFIG_ROOT:-./storage/config}/gitaly/:/etc/gitlab/gitaly
      - ${GITLAB_CONFIG_ROOT:-./storage/config}/gitlab-shell:/etc/gitlab/gitlab-shell
      - ${GITLAB_LOG_ROOT:-./storage/log}/gitaly:/var/log/gitaly
      - sockets:/home/git/run/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
  gitlab-shell:
    image: alpinelinux/gitlab-shell:$GITLAB_SHELL_VERSION
    restart: always
    build:
      context: ./gitlab-shell
      args:
        - ALPINE_VERSION
        - GITLAB_SHELL_VERSION
    ports:
      - 127.0.0.1:2222:22
    volumes:
      - ${GITLAB_CONFIG_ROOT:-./storage/config}/gitlab-shell:/etc/gitlab/gitlab-shell
      - ${GITLAB_CONFIG_ROOT:-./storage/config}/ssh:/etc/gitlab/ssh
      - ${GITLAB_LOG_ROOT:-./storage/log}:/var/log
      - ssh-authorized-keys:/home/git/.ssh/
      - sockets:/home/git/run/
      - gitlab-secret:/etc/gitlab/gitlab-shell/secret
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ${GITLAB_STORAGE_ROOT:-./storage}/redis:/data
    entrypoint: redis-server --appendonly yes
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - gitlab
    volumes:
      -  ${GITLAB_CONFIG_ROOT:-./storage/config}/registry:/etc/docker/registry/
      -  ${GITLAB_CONFIG_ROOT:-./storage}/certs/registry/public:/etc/docker/certs

volumes:
  sockets:
  ssh-authorized-keys:
  gitlab-secret:
