# https://taskfile.dev

version: '3'

dotenv: [build-args.env]

env:
  DOCKER_BUILDKIT: 1

tasks:
  build-args:
    cmds:
      - GITLAB_VERSION=$(<GITLAB-VERSION) build/versions.sh >build-args.env
    generates:
      - build-args.env
    sources:
      - build/versions.sh
      - GITLAB-VERSION

  .deploy-libs:
    cmds:
      - |-
        [[ -z "{{.project}}" ]] && { echo "\$project not provided"; exit 1; }
        install -Dm0644 lib/* -t {{.project}}/build/lib/
    sources:
      - lib/libsetup
    generates:
      - "{{.project}}/build/lib/libsetup"

  deploy-libs-gitaly:
    cmds:
      - task: .deploy-libs
        vars: {project: gitaly}
  build-gitaly:
    cmds:
      - docker-compose build gitaly
    deps:
      - build-args
      - deploy-libs-gitaly
      - build-gitlab-shell
    sources:
      - gitaly/*
      - gitaly/**/*

  deploy-libs-gitlab-shell:
    cmds:
      - task: .deploy-libs
        vars: {project: gitlab-shell}
  build-gitlab-shell:
    cmds:
      - docker-compose build gitlab-shell
    deps:
      - build-args
      - deploy-libs-gitlab-shell
    sources:
      - gitlab-shell/*
      - gitlab-shell/**/*
  config:
    cmds:
      - docker-compose config
